spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

server:
  port: 0
 
eureka:
  client:
    service-url:
      defaultZone: http://kleberlzms-eureka-user:erlseeakrer-sbzluk-ume@localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*' # Expondo os endpoints pro Actuator (Somente os MicroServiços)

logging:
  file:
    name: ./logs/log-file.log # Acessar o LOG no browser através do Actuator
